name: car_service
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
#  splashscreen: ^1.2.0
#  carousel_pro: ^1.0.0
#  carousel_slider: ^1.4.1
#  flutter_auth_buttons: ^0.9.0
#  flutter_signin_button: ^1.0.0
#  social_media_buttons: ^0.1.2
#  firebase_auth: ^0.16.1
#  curved_navigation_bar: ^0.3.3
#  geolocator: ^5.3.2+2
#  permission_handler: ^5.0.1+1
#  google_maps_flutter: ^0.5.30
#  autocomplete_textfield: ^1.7.3
#  flutter_calendar_carousel: ^1.4.12
#  flutter_form_builder: ^3.13.2
#  flutter_swiper: ^1.1.6
#  location: ^2.3.5
#  auto_size_text: ^2.1.0
#  fluttertoast: ^7.0.2
#  flutter_datetime_picker: ^1.4.0
#  datetime_picker_formfield: ^1.0.0
#  badges: ^1.1.1
#  intro_slider: ^2.3.1

#  animated_text_kit: ^2.2.0
#  qr_flutter: ^3.2.0
#  local_auth: ^0.6.2+3
#  flutter_screenutil: ^2.3.1
#  google_sign_in: ^4.5.1
#  path_provider: ^1.6.11
#  country_pickers: ^1.3.0
#  place_picker: ^0.9.14
#  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.1.0
  sqflite: ^1.3.1+1
  flutter_bloc: ^6.0.5
  path: ^1.7.0
  path_provider: any
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.1
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
#  provider: ^4.0.4
#  path_provider: ^0.5.0+1
  image: ^2.0.7
  multi_select_item: ^1.0.3
  intl:
  flutter_datetime_picker: ^1.4.0
  datetime_picker_formfield: ^1.0.0
  flutter_form_builder: ^3.13.2
  provider: ^4.3.1
  table_calendar: ^2.2.3
  url_launcher: ^5.1.2
  flutter_launcher_icons: ^0.7.0
  flutter_local_notifications: ^1.4.4+2
  flutter_dialogflow: ^0.1.0
  bubble:

flutter_icons:
  image_path: "assets/logo2.png"
  ios: true
  android: true


#  image_picker: ^0.6.7+4
#  timeline_tile: ^0.1.2
#  flutter_showcase: ^0.1.0
#  flutter_speed_dial: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - intro.jpg
     - carmoving.gif
     - ez.gif
     - thirdintro.png
     - car.jpg
     - bsm.jpg
     - cost.jpg
     - amc.jpg
     - img1.jpeg
     - img2.jpeg
     - img3.jpeg
     - img4.jpeg
     - img5.jpeg
     - img6.jpeg
     - img7.jpeg
     - img8.jpeg
     - img9.jpeg
     - img10.jpeg
     - img11.jpeg
     - img12.jpeg
     - img13.jpeg
     - img14.jpeg
     - img15.jpeg
     - img16.jpeg
     - img17.jpeg
     - img18.jpeg
     - img19.jpeg
     - img20.jpeg
     - pay.jpg
     - default.jpg
     - robot.jpg
     - assets/vehicleservicebot-wmpt-ae126c2fc250.json
     - logo.png
     - logo.jpg
     - logo1.png
     - logo2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
